# -----------------------------------------------------------------------------
# outputs.tf - the inventory, and the bill.
#
# The main output is a ready-to-use Ansible inventory, written by
# `terraform output -raw ansible_inventory > ../inventory/kernel-aws.yml`.
#
# Rendering it from state rather than asking people to paste addresses is the
# same instinct as lab 3's renderer: the machine that created the instances is
# the one that knows their addresses, and a hand-copied address is a hand-copied
# address. The alternative for a real fleet is the aws_ec2 dynamic inventory
# (../inventory/aws_ec2.yml), which is what production uses - this rig gets a
# static file because four throwaway instances do not need an API call per play,
# and because it makes the test runnable with no AWS credentials on the
# controller once the rig is up.
# -----------------------------------------------------------------------------

output "ansible_inventory" {
  description = "Ansible inventory for the rig. Redirect to ../inventory/kernel-aws.yml."
  value       = <<-EOT
    ---
    # GENERATED by `terraform output -raw ansible_inventory` in labs/lab2-ansible/aws/
    #
    # Four EC2 instances, one per distribution family, tuned by the same role
    # and the same profiles as the containers and the local VMs. Regenerate
    # after any apply; do not edit.
    #
    # The kernel_profile of each host comes from the KernelProfile TAG, which
    # Terraform set - so it is here as data, not as a decision made twice.
    all:
      children:
        kernel_tuned:
          children:
            kernel_aws:
              vars:
                ansible_connection: ssh
                ansible_become: true
                ansible_ssh_private_key_file: ${replace(var.ssh_public_key_path, ".pub", "")}
                ansible_ssh_common_args: >-
                  -o StrictHostKeyChecking=no
                  -o UserKnownHostsFile=/dev/null
                  -o ConnectTimeout=15
              hosts:
    %{~for name, i in aws_instance.test~}
                ${i.tags.Name}:
                  ansible_host: ${i.public_ip}
                  ansible_user: ${i.tags.LoginUser}
                  kernel_profile: ${i.tags.KernelProfile}
                  kernel_isolated_cpus: "${i.tags.IsolatedCpus}"
                  kernel_hugepages_1g: 1
                  kernel_idle_poll: false
                  ec2_instance_id: ${i.id}
    %{~endfor~}
  EOT
}

output "instances" {
  description = "What was created, with the AMI each one resolved to."
  value = {
    for name, i in aws_instance.test : i.tags.Name => {
      instance_id = i.id
      public_ip   = i.public_ip
      ami         = i.ami
      profile     = i.tags.KernelProfile
      login       = "ssh -i ${replace(var.ssh_public_key_path, ".pub", "")} ${i.tags.LoginUser}@${i.public_ip}"
    }
  }
}

output "reboot_command" {
  description = "Rebooting through the EC2 API rather than the OS - which is what an instance refresh does."
  value       = "aws ec2 reboot-instances --region ${var.region} --instance-ids ${join(" ", [for i in aws_instance.test : i.id])}"
}

output "running_cost_usd_per_hour" {
  description = "On-demand cost while this rig exists. Printed so it is on screen rather than in a bill."
  value = format(
    "%.3f USD/hour for %d x %s + %d x 20GB gp3 - run `terraform destroy` when finished",
    length(aws_instance.test) * 0.0168 + length(aws_instance.test) * 20 * 0.08 / 730,
    length(aws_instance.test),
    var.instance_type,
    length(aws_instance.test),
  )
}
