#!/usr/bin/env python3
"""Render every build artifact from hosts.yml - after validating it.

    ./scripts/render.py                # validate, then render all hosts
    ./scripts/render.py canon-gw01     # validate everything, render one host

Outputs (out/ is gitignored - artifacts are always regenerated, never edited):
    out/ks/<mac>.cfg                    kickstart, at the exact path boot.ipxe requests
    out/dhcpd-hosts.conf                ISC DHCP reservations
    out/inventory.yml                   Ansible inventory for the post-build handoff
    out/cloud-init/<hostname>.yaml      EC2 user data, from cloud-hosts.yml
    out/aws/instances.auto.tfvars.json  input to the Terraform root that creates them
    out/aws/inventory-preview.yml       the Ansible groups those TAGS will produce

The kickstart template uses {{ key }} placeholders. A placeholder with no value
in inventory is a hard error naming the host and the key - never an empty
string silently written into an answer file.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE / "scripts"))
from validate_hosts import (load_cloud_hosts, load_hosts,  # noqa: E402
                             validate, validate_cloud)

TEMPLATE = HERE / "kickstart" / "rhel9-min.ks.j2"
OUT = HERE / "out"
PLACEHOLDER = re.compile(r"{{\s*([a-z_]+)\s*}}")


class RenderError(Exception):
    pass


def mac_filename(mac):
    """3c:ec:ef:11:22:33 -> 3c-ec-ef-11-22-33 (iPXE's ${mac:hexhyp})."""
    return mac.replace(":", "-")


def netmask(prefix):
    bits = (0xFFFFFFFF << (32 - int(prefix))) & 0xFFFFFFFF
    return ".".join(str((bits >> s) & 0xFF) for s in (24, 16, 8, 0))


def render_kickstart(host, template_text):
    ctx = dict(host)
    ctx["bond_members"] = ",".join(host["bond_members"])
    ctx["netmask"] = netmask(host["prefix"])

    def sub(match):
        key = match.group(1)
        if key not in ctx or ctx[key] in (None, ""):
            raise RenderError(f"{host['hostname']}: template wants '{key}', inventory has no value for it")
        return str(ctx[key])

    return PLACEHOLDER.sub(sub, template_text)


def render_dhcp(hosts):
    lines = ["# GENERATED by scripts/render.py from hosts.yml - do not edit.",
             "# Include once from dhcpd.conf at global scope (host declarations are global).", ""]
    for h in hosts:
        lines += [f"host {h['hostname']} {{",
                  f"  hardware ethernet {h['mac']};",
                  f"  fixed-address {h['ip']};",
                  f"  option host-name \"{h['hostname']}\";",
                  "}", ""]
    return "\n".join(lines)


def render_inventory(hosts):
    """The handoff: newly built servers enter configuration management as data.

    Groups mirror Lab 2's axes - what it is (rhel9), what it runs (role), and
    where it is (rack) - plus `newly_built`, which acceptance.yml targets.
    """
    by_role, by_rack = {}, {}
    for h in hosts:
        by_role.setdefault(h["role"], []).append(h["hostname"])
        by_rack.setdefault(h["rack"].lower().replace("-", "_"), []).append(h["hostname"])

    out = ["# GENERATED by scripts/render.py from hosts.yml - do not edit.",
           "all:", "  children:", "    rhel9:", "      hosts:"]
    for h in hosts:
        out.append(f"        {h['hostname']}: {{ ansible_host: {h['ip']}, expected_ip: {h['ip']} }}")
    out += ["    newly_built:", "      children:", "        rhel9: {}"]
    for role, names in sorted(by_role.items()):
        out += [f"    {role}:", "      hosts:"] + [f"        {n}: {{}}" for n in names]
    for rack, names in sorted(by_rack.items()):
        out += [f"    rack_{rack}:", "      hosts:"] + [f"        {n}: {{}}" for n in names]
    return "\n".join(out) + "\n"


# =============================================================================
# The cloud half: from cloud-hosts.yml to three artifacts.
# =============================================================================

# The tag contract. These exact keys are what lab 1's Terraform module stamps on
# every resource (aws/modules/app_stack/main.tf) and what lab 2's aws_ec2
# inventory builds its groups from (inventory/aws_ec2.yml). Rendering them from
# the same record that produces the instance is what keeps the three in step:
# nobody maintains a second list, so there is no second list to drift.
def cloud_tags(host):
    return {
        "Name": host["hostname"],
        "Environment": host["environment"],
        "Role": host["role"],
        "Service": host["service"],
        "ManagedBy": "terraform",
        "Module": "baremetal_handoff",
        "KernelProfile": host["kernel_profile"],
    }


def render_tfvars(cloud_hosts):
    """Terraform input, keyed by hostname.

    A MAP keyed by name, not a list - the same reason lab 1's module takes a map:
    removing one instance from this file must destroy that one instance, not
    renumber the others and replace everything after it.
    """
    return json.dumps({
        "instances": {
            h["hostname"]: {
                "instance_type": h["instance_type"],
                "availability_zone": h["availability_zone"],
                "volume_size": int(h["volume_size"]),
                "tags": cloud_tags(h),
            }
            for h in cloud_hosts
        }
    }, indent=2, sort_keys=True) + "\n"


def render_cloud_init(host):
    """EC2 user data: the cloud equivalent of the kickstart %post section.

    And it does as little as the kickstart's %post does, for the same reason. A
    user-data script runs ONCE, on first boot, and is then invisible forever -
    so anything configured here is drift nobody can detect. Everything that has
    to stay correct belongs to lab 2's roles, which run again and again.

    What legitimately belongs here is only what must be true BEFORE
    configuration management can run at all: identity, and the agent that lets
    the controller connect.
    """
    tags = cloud_tags(host)
    return f"""#cloud-config
# GENERATED by scripts/render.py from cloud-hosts.yml - do not edit.
#
# {host['hostname']}: {host['role']}/{host['service']} in {host['environment']}
#
# Deliberately minimal. See the docstring in scripts/render.py: user data runs
# once and can never be re-asserted, so it sets identity and the SSM agent and
# then hands the host to Ansible.

# Set the hostname permanently, not just for this boot. Without
# preserve_hostname the cloud-init default rewrites it from the private DNS
# name on every boot, and the Ansible inventory name stops matching the host -
# which breaks patch.yml's pre-flight assertion on purpose, and every per-host
# record by accident.
hostname: {host['hostname']}
fqdn: {host['hostname']}.{host['environment']}.canon.example
preserve_hostname: false
manage_etc_hosts: true

# NO package upgrades on first boot.
#
# It is tempting, and it makes every instance in an Auto Scaling group a
# different machine depending on the minute it launched - the same reason lab
# 2's baseline role installs `state: present` and never `latest`. Patching is
# a deliberate, batched operation with a health gate: that is patch.yml's job.
package_update: false
package_upgrade: false

packages:
  - amazon-ssm-agent

runcmd:
  # The agent is what lets the controller reach this instance with no inbound
  # rule, no bastion and no SSH key - see lab 2's
  # inventory/group_vars/aws_ec2.yml.
  - [systemctl, enable, --now, amazon-ssm-agent]

write_files:
  # The identity this host claims, for the acceptance test to compare against
  # what the inventory says it should be. The same contract as the physical
  # build: acceptance.yml asserts the host is what the source of truth says.
  - path: /etc/canon-identity
    permissions: '0644'
    content: |
      hostname={host['hostname']}
      role={host['role']}
      service={host['service']}
      environment={host['environment']}
      kernel_profile={host['kernel_profile']}
      source=cloud-hosts.yml

# Fail loudly. Without this, a failed user-data run leaves an instance that is
# running, healthy to the load balancer, and not actually configured - which is
# the cloud version of a server that installed and never registered.
output:
  all: '| tee -a /var/log/cloud-init-output.log'
"""


def render_inventory_preview(cloud_hosts):
    """Prove the tag contract offline, before anything is created.

    Lab 2's inventory/aws_ec2.yml builds groups from tags with `keyed_groups`.
    Lab 1's Terraform stamps those tags. Nothing checks that the tags actually
    produce the groups the playbooks target - so a typo in a tag value means
    `--limit tag_Role_db` matches nothing, the play reports "no hosts matched",
    and exits 0. A rollout that silently touched zero hosts is the worst
    possible outcome: it looks like success.

    This renders the groups those keyed_groups WILL produce from these tags, so
    the contract is reviewable in a pull request and testable with no AWS
    account. tests/test_source_of_truth.py asserts the groups the playbooks
    depend on are present.
    """
    groups = {}
    for host in cloud_hosts:
        tags = cloud_tags(host)
        for group in (f"tag_Service_{tags['Service']}",
                      f"tag_Environment_{tags['Environment']}",
                      f"tag_Role_{tags['Role']}",
                      f"az_{host['availability_zone'].replace('-', '_')}",
                      f"type_{host['instance_type'].replace('.', '_')}"):
            groups.setdefault(group, []).append(host["hostname"])

    out = ["# GENERATED by scripts/render.py from cloud-hosts.yml - do not edit.",
           "#",
           "# The groups lab 2's inventory/aws_ec2.yml will produce from these tags.",
           "# This file is NOT an inventory to run against - the real one comes from the",
           "# EC2 API. It exists so the Terraform-to-Ansible tag contract can be reviewed",
           "# and tested without an AWS account.",
           "all:",
           "  children:"]
    for group, names in sorted(groups.items()):
        out += [f"    {group}:", "      hosts:"] + [f"        {n}: {{}}" for n in sorted(names)]
    return "\n".join(out) + "\n"


def main(argv):
    hosts = load_hosts()
    errors = [("hosts.yml", e) for e in validate(hosts)]

    cloud_path = HERE / "cloud-hosts.yml"
    cloud_hosts = load_cloud_hosts(cloud_path) if cloud_path.exists() else []
    errors += [("cloud-hosts.yml", e) for e in validate_cloud(cloud_hosts, hosts)]

    # Nothing is rendered if EITHER record set is wrong. Rendering the valid
    # half would leave out/ holding a mix of current and stale artifacts, which
    # is harder to debug than no artifacts at all.
    if errors:
        print(f"refusing to render: {len(errors)} error(s) in the source of truth")
        for source, e in errors:
            print(f"  - {source}: {e}")
        return 1

    wanted = set(argv)
    unknown = wanted - {h["hostname"] for h in hosts} - {h["hostname"] for h in cloud_hosts}
    if unknown:
        print(f"unknown host(s): {', '.join(sorted(unknown))}")
        return 1
    selected = [h for h in hosts if not wanted or h["hostname"] in wanted]

    template_text = TEMPLATE.read_text()
    (OUT / "ks").mkdir(parents=True, exist_ok=True)
    try:
        for h in selected:
            path = OUT / "ks" / f"{mac_filename(h['mac'])}.cfg"
            path.write_text(render_kickstart(h, template_text))
            print(f"{h['hostname']:<12} {h['mac']}  ->  out/ks/{path.name}")
    except RenderError as exc:
        print(f"ERROR: {exc}")
        return 1

    (OUT / "dhcpd-hosts.conf").write_text(render_dhcp(hosts))
    (OUT / "inventory.yml").write_text(render_inventory(hosts))
    print(f"{'':<12} {len(hosts)} reservation(s)  ->  out/dhcpd-hosts.conf")
    print(f"{'':<12} ansible handoff    ->  out/inventory.yml")

    # --- the cloud half -------------------------------------------------------
    if cloud_hosts:
        selected_cloud = [h for h in cloud_hosts if not wanted or h["hostname"] in wanted]
        (OUT / "cloud-init").mkdir(parents=True, exist_ok=True)
        (OUT / "aws").mkdir(parents=True, exist_ok=True)
        for h in selected_cloud:
            path = OUT / "cloud-init" / f"{h['hostname']}.yaml"
            path.write_text(render_cloud_init(h))
            print(f"{h['hostname']:<12} {h['instance_type']:<18}  ->  out/cloud-init/{path.name}")
        (OUT / "aws" / "instances.auto.tfvars.json").write_text(render_tfvars(cloud_hosts))
        (OUT / "aws" / "inventory-preview.yml").write_text(render_inventory_preview(cloud_hosts))
        print(f"{'':<12} {len(cloud_hosts)} instance(s)     ->  out/aws/instances.auto.tfvars.json")
        print(f"{'':<12} tag contract       ->  out/aws/inventory-preview.yml")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
