#!/usr/bin/env python3
"""Render every build artifact from hosts.yml - after validating it.

    ./scripts/render.py                # validate, then render all hosts
    ./scripts/render.py canon-gw01     # validate everything, render one host

Outputs (out/ is gitignored - artifacts are always regenerated, never edited):
    out/ks/<mac>.cfg        kickstart, at the exact path boot.ipxe requests
    out/dhcpd-hosts.conf    ISC DHCP reservations
    out/inventory.yml       Ansible inventory for the post-build handoff

The kickstart template uses {{ key }} placeholders. A placeholder with no value
in inventory is a hard error naming the host and the key - never an empty
string silently written into an answer file.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE / "scripts"))
from validate_hosts import load_hosts, validate  # noqa: E402

TEMPLATE = HERE / "kickstart" / "rhel9-min.ks.j2"
OUT = HERE / "out"
PLACEHOLDER = re.compile(r"{{\s*([a-z_]+)\s*}}")


class RenderError(Exception):
    pass


def mac_filename(mac):
    """3c:ec:ef:11:22:33 -> 3c-ec-ef-11-22-33 (iPXE's ${mac:hexhyp})."""
    return mac.replace(":", "-")


def netmask(prefix):
    bits = (0xFFFFFFFF << (32 - int(prefix))) & 0xFFFFFFFF
    return ".".join(str((bits >> s) & 0xFF) for s in (24, 16, 8, 0))


def render_kickstart(host, template_text):
    ctx = dict(host)
    ctx["bond_members"] = ",".join(host["bond_members"])
    ctx["netmask"] = netmask(host["prefix"])

    def sub(match):
        key = match.group(1)
        if key not in ctx or ctx[key] in (None, ""):
            raise RenderError(f"{host['hostname']}: template wants '{key}', inventory has no value for it")
        return str(ctx[key])

    return PLACEHOLDER.sub(sub, template_text)


def render_dhcp(hosts):
    lines = ["# GENERATED by scripts/render.py from hosts.yml - do not edit.",
             "# Include once from dhcpd.conf at global scope (host declarations are global).", ""]
    for h in hosts:
        lines += [f"host {h['hostname']} {{",
                  f"  hardware ethernet {h['mac']};",
                  f"  fixed-address {h['ip']};",
                  f"  option host-name \"{h['hostname']}\";",
                  "}", ""]
    return "\n".join(lines)


def render_inventory(hosts):
    """The handoff: newly built servers enter configuration management as data.

    Groups mirror Lab 2's axes - what it is (rhel9), what it runs (role), and
    where it is (rack) - plus `newly_built`, which acceptance.yml targets.
    """
    by_role, by_rack = {}, {}
    for h in hosts:
        by_role.setdefault(h["role"], []).append(h["hostname"])
        by_rack.setdefault(h["rack"].lower().replace("-", "_"), []).append(h["hostname"])

    out = ["# GENERATED by scripts/render.py from hosts.yml - do not edit.",
           "all:", "  children:", "    rhel9:", "      hosts:"]
    for h in hosts:
        out.append(f"        {h['hostname']}: {{ ansible_host: {h['ip']}, expected_ip: {h['ip']} }}")
    out += ["    newly_built:", "      children:", "        rhel9: {}"]
    for role, names in sorted(by_role.items()):
        out += [f"    {role}:", "      hosts:"] + [f"        {n}: {{}}" for n in names]
    for rack, names in sorted(by_rack.items()):
        out += [f"    rack_{rack}:", "      hosts:"] + [f"        {n}: {{}}" for n in names]
    return "\n".join(out) + "\n"


def main(argv):
    hosts = load_hosts()
    errors = validate(hosts)
    if errors:
        print(f"refusing to render: hosts.yml has {len(errors)} error(s)")
        for e in errors:
            print(f"  - {e}")
        return 1

    wanted = set(argv)
    unknown = wanted - {h["hostname"] for h in hosts}
    if unknown:
        print(f"unknown host(s): {', '.join(sorted(unknown))}")
        return 1
    selected = [h for h in hosts if not wanted or h["hostname"] in wanted]

    template_text = TEMPLATE.read_text()
    (OUT / "ks").mkdir(parents=True, exist_ok=True)
    try:
        for h in selected:
            path = OUT / "ks" / f"{mac_filename(h['mac'])}.cfg"
            path.write_text(render_kickstart(h, template_text))
            print(f"{h['hostname']:<12} {h['mac']}  ->  out/ks/{path.name}")
    except RenderError as exc:
        print(f"ERROR: {exc}")
        return 1

    (OUT / "dhcpd-hosts.conf").write_text(render_dhcp(hosts))
    (OUT / "inventory.yml").write_text(render_inventory(hosts))
    print(f"{'':<12} {len(hosts)} reservation(s)  ->  out/dhcpd-hosts.conf")
    print(f"{'':<12} ansible handoff    ->  out/inventory.yml")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
